services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 5001
      DATABASE_URL: mysql://user:password@db:3306/miniclickup
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: miniclickup-container
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: miniclickup
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "-ppassword"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db-data: